name: BookMailbox
main: com.modcrafting.bookmailbox.BookMailbox
version: 0.1
website: http://modcrafting.com
author: Deathmarine
description: >
             Plugin for Bukkit.
             
commands:
  mail:
    description: Command Access
    usage: /<command>
permissions:
  bookmailbox.*:
    description: Allows the Administration to Full Control
    children:
      bookmailbox.command: true
      bookmailbox.admin: true
  bookmailbox.command:
    default: op
    description: Allows player to send mail
  bookmailbox.admin:
    description: Allows player administrator to access any mailbox
    